[workspace]
# GitHub Releases + tags are enabled by default; leave publish off for now.
publish = false
git_release_enable = true
git_tag_enable = true
# Only publish when the Release PR is merged (not on every push).
release_always = false
# Optional: add labels to the Release PR
pr_labels = ["release", "automation"]

# Changelog rendering (release-plz uses git-cliff internally)
[changelog]
header = "# Changelog"
trim = true
protect_breaking_commits = true
sort_commits = "newest"
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^style", group = "Style" },
    { message = "^docs", group = "Documentation" },
    { message = "^build", group = "Build System" },
    { message = "^ci", group = "CI" },
    { message = "^test", group = "Tests" },
    { message = "^revert", group = "Reverts" },
    { message = "^chore", group = "Chores", skip = true },
]

# Keep all crates in lockstep and write to the single root CHANGELOG.md
[[package]]
name = "pipeline-domain"
version_group = "core"
changelog_path = "CHANGELOG.md"
# semver_check defaults to true for libs; keep it on.

[[package]]
name = "pipeline"
version_group = "core"
changelog_path = "CHANGELOG.md"

[[package]]
name = "bootstrap"
version_group = "core"
changelog_path = "CHANGELOG.md"
