# Rustfmt configuration (stable-compatible only)
# Nightly-only features removed for CI compatibility

max_width = 120
tab_spaces = 4
edition = "2021"
use_field_init_shorthand = true

# Nightly-only features (commented out - enable locally with nightly if desired):
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# format_strings = true
# imports_granularity = "Module"
# wrap_comments = true
