# Cross compilation configuration
# https://github.com/cross-rs/cross

[build]
# Use pre-built Docker images (don't try to install host toolchains)
pre-build = []

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:latest"

# Note: macOS targets don't have official cross images
# They will fall back to native cargo builds
