-- Generated by ID Generator - SOURCE OF TRUTH for Database
-- This script creates a fresh database with proper ULID format IDs
-- Generated at: 2025-07-10 02:29:34 UTC

-- Clean slate - drop all tables
DROP TABLE IF EXISTS stage_parameters;
DROP TABLE IF EXISTS pipeline_stages;
DROP TABLE IF EXISTS pipeline_configuration;
DROP TABLE IF EXISTS processing_metrics;
DROP TABLE IF EXISTS processing_sessions;
DROP TABLE IF EXISTS file_chunks;
DROP TABLE IF EXISTS security_contexts;
DROP TABLE IF EXISTS pipelines;

-- Create schema
CREATE TABLE pipelines (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE pipeline_configuration (
    pipeline_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (pipeline_id, key),
    FOREIGN KEY (pipeline_id) REFERENCES pipelines(id)
);

CREATE TABLE pipeline_stages (
    id TEXT PRIMARY KEY,
    pipeline_id TEXT NOT NULL,
    name TEXT NOT NULL,
    stage_type TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    stage_order INTEGER NOT NULL,
    algorithm TEXT NOT NULL,
    parallel_processing BOOLEAN NOT NULL DEFAULT FALSE,
    chunk_size INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (pipeline_id) REFERENCES pipelines(id)
);

CREATE TABLE stage_parameters (
    stage_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (stage_id, key),
    FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id)
);

CREATE TABLE processing_metrics (
    pipeline_id TEXT PRIMARY KEY,
    bytes_processed INTEGER NOT NULL DEFAULT 0,
    bytes_total INTEGER NOT NULL DEFAULT 0,
    chunks_processed INTEGER NOT NULL DEFAULT 0,
    chunks_total INTEGER NOT NULL DEFAULT 0,
    start_time_rfc3339 TEXT,
    end_time_rfc3339 TEXT,
    processing_duration_ms INTEGER,
    throughput_bytes_per_second REAL NOT NULL DEFAULT 0.0,
    compression_ratio REAL,
    error_count INTEGER NOT NULL DEFAULT 0,
    warning_count INTEGER NOT NULL DEFAULT 0,
    input_file_size_bytes INTEGER NOT NULL DEFAULT 0,
    output_file_size_bytes INTEGER NOT NULL DEFAULT 0,
    input_file_checksum TEXT,
    output_file_checksum TEXT,
    FOREIGN KEY (pipeline_id) REFERENCES pipelines(id)
);

-- Insert pipelines with proper ULID format
INSERT INTO pipelines (id, name, archived, created_at, updated_at) VALUES
('01JZS2ND3SRJJGPJHNJSEXTY2M', 'test-multi-stage', false, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
('01JZS2ND3SZ98HC0FV3JEZ9R1F', 'image-processing', false, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z');

-- Insert pipeline configuration
INSERT INTO pipeline_configuration (pipeline_id, key, value) VALUES
('01JZS2ND3SRJJGPJHNJSEXTY2M', 'encryption_algorithm', 'aes256gcm'),
('01JZS2ND3SRJJGPJHNJSEXTY2M', 'compression_algorithm', 'brotli'),
('01JZS2ND3SRJJGPJHNJSEXTY2M', 'chunk_size_mb', '1'),
('01JZS2ND3SZ98HC0FV3JEZ9R1F', 'max_file_size', '100MB'),
('01JZS2ND3SZ98HC0FV3JEZ9R1F', 'output_format', 'JPEG'),
('01JZS2ND3SZ98HC0FV3JEZ9R1F', 'quality', '85');

-- Insert pipeline stages (4 stages for test-multi-stage, 2 for image-processing)
INSERT INTO pipeline_stages (id, pipeline_id, name, stage_type, enabled, stage_order, algorithm, parallel_processing, chunk_size, created_at, updated_at) VALUES
-- test-multi-stage stages (4 total)
('01JZS2ND3S4FT027T27S3DYC2V', '01JZS2ND3SRJJGPJHNJSEXTY2M', 'input_checksum', 'Custom', true, 0, 'sha256', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
('01JZS2ND3SAEY4MZHA1M4Z2V45', '01JZS2ND3SRJJGPJHNJSEXTY2M', 'compression', 'Custom', true, 1, 'brotli', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
('01JZS2ND3S0PVN1AAGVCP954MW', '01JZS2ND3SRJJGPJHNJSEXTY2M', 'encryption', 'Custom', true, 2, 'aes256gcm', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
('01JZS2ND3S3NQKBASFFBZ9HSBK', '01JZS2ND3SRJJGPJHNJSEXTY2M', 'output_checksum', 'Custom', true, 3, 'sha256', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
-- image-processing stages (2 total)
('01JZS2ND3SSZH7G4KACQZHSVEE', '01JZS2ND3SZ98HC0FV3JEZ9R1F', 'input_validation', 'Custom', true, 0, 'sha256', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z'),
('01JZS2ND3SEB3PN4WTR6ZCG3AT', '01JZS2ND3SZ98HC0FV3JEZ9R1F', 'image_compression', 'Custom', true, 1, 'jpeg', false, null, '2025-07-09T19:28:00Z', '2025-07-09T19:28:00Z');

-- Insert stage parameters
INSERT INTO stage_parameters (stage_id, key, value) VALUES
('01JZS2ND3SAEY4MZHA1M4Z2V45', 'level', '6'),
('01JZS2ND3SEB3PN4WTR6ZCG3AT', 'compression_level', '6');

-- Insert processing metrics (initialized to zero)
INSERT INTO processing_metrics (pipeline_id) VALUES
('01JZS2ND3SRJJGPJHNJSEXTY2M'),
('01JZS2ND3SZ98HC0FV3JEZ9R1F');

-- Verification query
SELECT 'pipelines' as table_name, COUNT(*) as count FROM pipelines
UNION ALL
SELECT 'pipeline_configuration', COUNT(*) FROM pipeline_configuration
UNION ALL
SELECT 'pipeline_stages', COUNT(*) FROM pipeline_stages
UNION ALL
SELECT 'stage_parameters', COUNT(*) FROM stage_parameters
UNION ALL
SELECT 'processing_metrics', COUNT(*) FROM processing_metrics;

-- Success message
SELECT 'Database created successfully with proper ULID format!' as status;
