name: CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-test:
        name: build & test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - run: cargo build --workspace --all-targets --locked
            - run: cargo test  --workspace --all-features --locked

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - run: rustup component add rustfmt
            - run: cargo fmt --all -- --check

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy
            - uses: Swatinem/rust-cache@v2

            # Clippy strict on production code (lib/bins only - denies unwrap/expect/panic)
            # Tests are allowed to use unwrap/expect and are not checked here
            - name: Clippy (production code)
              run: cargo clippy --workspace --lib --bins --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used -D clippy::panic -D clippy::todo -D clippy::unimplemented

    semver-pipeline-domain:
        name: semver (adaptive-pipeline-domain)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: { fetch-depth: 0 }
            - name: Find last release tag for adaptive-pipeline-domain
              id: baseline
              run: |
                  echo "BASELINE_TAG=$(git describe --tags --match 'adaptive-pipeline-domain-v*' --abbrev=0 || echo '')" >> $GITHUB_ENV
            - name: No baseline? First release — skip check
              if: env.BASELINE_TAG == ''
              run: echo "No baseline tag found; skipping semver check."
            - name: cargo-semver-checks (against last tag)
              if: env.BASELINE_TAG != ''
              uses: obi1kenobi/cargo-semver-checks-action@v2
              with:
                  package: adaptive-pipeline-domain
                  baseline-revision: ${{ env.BASELINE_TAG }}
                  # derives required bump from Cargo.toml by default; override with "release-type" if needed
