name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'adaptive_pipeline/docs/**'
      - '**/README.md'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          mkdir -p $HOME/mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/mdbook
          echo "$HOME/mdbook" >> $GITHUB_PATH

      - name: Build documentation
        run: |
          # Build user guide (root docs)
          cd docs
          mdbook build
          cd ..

          # Build developer guide
          cd adaptive_pipeline/docs
          mdbook build
          cd ../..

          # Create combined deployment directory
          mkdir -p _site
          cp -r docs/book/* _site/
          mkdir -p _site/developer
          cp -r adaptive_pipeline/docs/book/* _site/developer/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
