name: Release-plz

on:
    push:
        branches: [main]
    workflow_dispatch: {}

jobs:
    # Publish unpublished releases (tags + GitHub Release, and crates.io if enabled).
    release-plz-release:
        name: Release-plz release
        runs-on: ubuntu-latest
        permissions:
            contents: write # needed to push tags & create releases
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Run release-plz
              uses: release-plz/[email protected]
              with:
                  command: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # Enable crates.io publish later by setting publish=true in .release-plz.toml
                  # and providing a token OR using trusted publishing (see note below).
                  # CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    # Create/refresh the Release PR (versions + CHANGELOG.md)
    release-plz-pr:
        name: Release-plz PR
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        concurrency:
            group: release-plz-${{ github.ref }}
            cancel-in-progress: false
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Run release-plz
              uses: release-plz/[email protected]
              with:
                  command: release-pr
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
